version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn lint
workflows:
  version: 2
  tests:
    jobs:
      - test
