version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - run: yarn test
      - run: yarn lint
workflows:
  version: 2
  tests:
    jobs:
      - test
